insert into tipoproducto (tipo) values ('Vacuna');
insert into tipoproducto (tipo) values ('Servicio');
insert into tipoproducto (tipo) values ('Accesorio');

insert into producto (producto, precio, IdTipo) values ('Triple - edad: 6 semanas', 120, 1);
insert into producto (producto, precio, IdTipo) values ('Parvovirus - edad: 8 semanas', 80, 1);
insert into producto (producto, precio, IdTipo) values ('Refuerzo de la Triple - edad: 10 semanas', 140, 1);
insert into producto (producto, precio, IdTipo) values ('Refuerzo de Parvovirus - edad: 12 semanas', 100, 1);
insert into producto (producto, precio, IdTipo) values ('Rabia - 16 semanas', 120, 1);
insert into producto (producto, precio, IdTipo) values ('Rabia - Anual', 150, 1);
insert into producto (producto, precio, IdTipo) values ('Parvovirus - Anual', 150, 1);
insert into producto (producto, precio, IdTipo) values ('Triple - Anual', 150, 1);

insert into producto (producto, precio, IdTipo) values ('Baño', 30, 2);
insert into producto (producto, precio, IdTipo) values ('Baño medicado', 50, 2);
insert into producto (producto, precio, IdTipo) values ('Corte', 20, 2);
insert into producto (producto, precio, IdTipo) values ('Profilaxis', 300, 2);
insert into producto (producto, precio, IdTipo) values ('Despulgada - FrontLine', 50, 2);
insert into producto (producto, precio, IdTipo) values ('Consulta', 20, 2);
insert into producto (producto, precio, IdTipo) values ('Esterilizado', 100, 2);

insert into producto (producto, precio, IdTipo) values ('Comida MiMascot 1 kg para cachorro', 10, 3);
insert into producto (producto, precio, IdTipo) values ('Comida MiMascot 1 kg para adulto', 15, 3);
insert into producto (producto, precio, IdTipo) values ('Comida MiMascot 5 kg para cachorro', 42, 3);
insert into producto (producto, precio, IdTipo) values ('Comida MiMascot 5 kg para adulto', 60, 3);
insert into producto (producto, precio, IdTipo) values ('Comida Balanceada R/D 3 kg', 97, 3);
insert into producto (producto, precio, IdTipo) values ('Comida Pedigree 1 Kg para cachorro', 12, 3);
insert into producto (producto, precio, IdTipo) values ('Comida Pedigree 1 Kg para adulto', 18, 3);
insert into producto (producto, precio, IdTipo) values ('Comida Pedigree 5 Kg para cachorro', 70, 3);
insert into producto (producto, precio, IdTipo) values ('Comida Pedigree 5 Kg para adulto', 60, 3);
insert into producto (producto, precio, IdTipo) values ('Comida RicoCat 1 Kg para cachorro', 13, 3);
insert into producto (producto, precio, IdTipo) values ('Comida RicoCat 5 Kg para cachorro', 56, 3);
insert into producto (producto, precio, IdTipo) values ('Cama - cachorro', 50, 3);
insert into producto (producto, precio, IdTipo) values ('Cama - adulto', 100, 3);
insert into producto (producto, precio, IdTipo) values ('Correa', 25, 3);
insert into producto (producto, precio, IdTipo) values ('Mordaza - Limpieza/Diente para cachorro', 20, 3);
insert into producto (producto, precio, IdTipo) values ('Mordaza - Limpieza/Diente para adulto', 40, 3);
insert into producto (producto, precio, IdTipo) values ('FrontLine - Spray', 60, 3);

insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARGARITA DE LA PIEDRA', 'margotcapie@hotmail.com', 'CAL. 24 DE JULIO 296 P.J. SIMON BOLIVAR ', '', '', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LUISA PARODI', '', 'TOMAS MARSANO  # 2124', '', '449-8998', '4498998 ', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SILVIA LUCILA ALBUQUERQUE F.', '', 'PASAJE JAEN  # 169  RAMON CASTILLA', '', '', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA LUISA MONTES', '', 'LOS CASTA-OS 405 SAN ISIDRO', '', '690 // 264-2393', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('HUMBERTO SATO', '', 'CAL. LA MERCED URB. LOS ALISOS MZA. D LOTE. 04 ', '', '5660290', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PATRICIA YESICA PEREZ HERRERA', '', 'LOS SAUCES  MZ. E  LT.  22   DPTO.  101', '', '', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RAMIREZ VILLALOBOS DELICIA MARGOT', '', 'AV. LUZURIAGA NRO. 834 ANCASH - HUARAZ - HUARAZ', '', '725689', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MERCEDES RIVAS PLATA', '', 'LOS TULIPANES    MZ.L  LT.  23', '', '', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ROLF KLINGENBERGER', '', 'AV. LA PAZ 1190', '', '444-8726', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CAROL M. BURNS', '', 'TUDELA Y VARELA 304', '', '441-8879', '536-7066 ', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JORGE BAERTL', '', 'GONZALES LARRA-AGA 180', '', '446-5994', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SOFIA FERREYRA', '', 'AV. AREQUIPA 4334  4to. PISO', '', '441-33-15', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DENNIS ACEVEDO', '', 'CALLE LOS ZAFIROS 150 BELLAVISTA', '', '918-9864', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('KATTY RODRIGEZ', '', 'AV ESTACION S/N', '', '246-4024', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ARQ. GONZALO GARCIA', '', 'DIESCANSECO 481 ALT. CDRA. 56 DE PASEO DE LA REPUBLICA', '', '4453502', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JOSE AGUSTIN CAMPOS PALACIOS', '', 'AV BOLOGNESI 230', '', '9099438', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIELA BERTORINI', '', 'ALAMEDA DE LA MOLINA VIEJA 604', '', '495-10-43', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ANCCO CAYO JOSE BENITO', 'BAJA DEFINITIVA', 'APV.MIGUEL GRAU ZONA SUR MZA. L LOTE. 2 ', '', '4844595', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LECIC BALARIN VESNA', '', 'CAL. EL ALAMO 228 201 C.C. MONTERRICO ', '', '435-6499', '3723867 ', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MANUEL RIVERA TOYAMA', '', 'JAVIER PRADO OESTE # 114', '', '', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JUAN JOSE KONJA CARRASCO', '', 'AV. ECHENIQUE 140', '', '', '', 1);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GINA BERNUY BLAKELEY', '', 'PJ. BUENOS AIRES 187 ', '', '242-22-12', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MESONES ANGULO ALVARO', '', 'TRINIDAD MORAN K6 URB. LEON XIII', '', '054-25-46-90', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BERTHA LAJARA', '', 'EDIFICIO LOS OLIVOS 103 C.H. RESIDENCIAL SAN FELIPE ', '', '2615013 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SAMUEL LEIVA SAENZ', '', 'AV. LUZURIAGA 483 - HUARAZ', '', '044-722265', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MANUEL ORRILLO PEÑA', '', 'AV. JOSE PARDO 138', '', '447-4738', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LUZ VELASQUEZ GUZMAN', '', 'JR. SAN MARTIN 643 ', '', '726114 044', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SILVIA CASABONA', '', 'LAGUNA BLANCA 167', '', '479-00-14', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SERGIO SOLER', '', 'CALLE INTIHUATONA 459', '', '448-4626', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOS MANUEL BARREDA', '', 'MONTE REAL 280 DPTO. 101', '', '932-50-40', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MALUYE MUSIRIS', '', 'AV. AURELIO MIRO QUESADA 520 RES. RESIDENCIAL DPTO. P17 ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LEONOR AVENDAÑO', '', 'MANUEL TOVAR 522 ENTRE CUADRA 11 Y 12 ANGAMOS OESTE', '', '06-24 441-33-50', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JAIME CHAN UNG', '', 'AV. UNIVERSITARIA 695', '', '566-11-04', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GALLIA PAREDES GUIDO HUGO', '', 'JR. LEON VELARDE NRO. 890', '', '4701446', '4705682', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PAMELA LOAYZA OSORIO', '', 'AV. LA PAZ # 476  DPTO. F', '', '5661833', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARISABEL TABOADA', '', 'MALECON 28 DE JULIO 301  DPTO. 1201', '', '9624411', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA DEL CARMEN BORJA', 'mbaborja@hotmail.com', 'CALLE EL SOLITARIO DE SAYAN 107 MARANGA', '', '578-1334', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOTA SEVIL', '', 'AV. CENTRAL 643 INT. 103 ', '', '793     8670465', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MIGUEL HITOTSUISHY', '', 'MAMA OCLLO 2115  DPTO. 404', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BRUNO ROCCO', '', 'CAL. PAJATEN 194 URB. LOS MANZANOS ', '', '727-0230', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOS GUINOZA', '', 'CAL. FRAY ANGELICO 540 DPTO. 202A ', '', '2251154', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MAGALI AITA', '', 'JR. MARCARA 124 ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('KARLA REATEGUI', '', 'Monte Real 187 - Dpto. 401', '', '372-7164', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA VIRGINIA BARBOSA RIBBECK', '', 'CAL. LOS HALCONES 664 URB. JARDIN ', '', '222-2087', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JHON DAVALOS', '', 'SECT 3 GRU. 10 MZA. G LOTE. 8', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ANDREA GOYENECHEA', '', 'AV. VICUS MZ.O LT40 URB. LA CAPULLANA ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FERNANDO HAWIE', '', 'CAL. BELLAVISTA 231 ', '', '479-0192', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ALEX LAGUNA ARANA', '', 'CAL. JUNIN 119 B URB. SAN GREGORIO ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ANA SAORI IJU FUKUSHIMA', '', 'CALLE LAS ALMEJAS MZ.U LOTE 2-3', '', '230-8311', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ANGELA ROCIO SAAVEDRA CARVO', '', 'JUAN FUENTES MZ. M LT.33', '', '2720802', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ARMANDO KOHATSU KANASHIRO', '', 'AV.GRAN CHIMU 383', '', '3761 / 376-3763', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BJARNI ODD PALOMINO SALAS', '', 'CAL. PAMPAS A 9 URB. LOS JAZMINES DEL NARANJAL ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOS TAMASHIRO ARAKAKI', '', 'AV ABANCAY 210 A', '', '0144 / 428-2825', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CONSUELO BARRETO', '', 'MZ. T LT.3-A JAHUAY LURIN', '', '2307054', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DAVID ASTUVILCA ALDERETE', '', 'PASAJE HUERTO  #  221', '', '574-2995', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DIONISIO AGUSTINO CASTAÑEDA GUARDIA', '', 'CALLE 5 MANZANA X3  LOTE 12 URB.LOS NARANJOS', '', '5210421', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ERMES MELINCHON LECARNAQUE', '', 'AV REPUBLICA DE PANAMA 5364', '', '60  /  446-2785', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FABIO RAFFO CONSIGLI', '', 'CAL. EMILIO FERNANDEZ 296 204 URB. SANTA BEATRIZ DPTO. 5 ', '', '442-9581', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FERNANDO MONTENEGRO TAYCA', '', 'C 5 COO. VIV LA FORTALEZA ', '', '450-0167', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GIANMARCO TAMASHIRO HIGA', '', 'AV. GRAL SANTA CRUZ 384 (COMISARIA DE JESUS MARIA)', '', '0181 / 460-0248', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DEL SOLAR QUIROS GRIMANESA MARIA', 'grimy@terra.com.pe', 'LEONIDAS AVENDA-O 235 - MIRAFLORES', '', '445-0796', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JAVIER LAZO', '', 'SECTOR D MZ C LT 13 ASOC.VISTA ALEGRE', '', '850-7296', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JESSICA SAYURI TAMASHIRO', '', 'AV NICOLAS DE PIEROLA 864 - 870', '', '423-5114', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JIMMY YAMASHIRO YAMAMOTO', '', 'AV PERU 3641', '', '-0099 / 5689114', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JORGE E. TATAJE WILCOX', 'bbv-gorgi@bolckbuster.com.pe', 'LOS FICUS 376', '', '7993 / 995-2255', '4417993 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('KARINA TAMASHIRO HIGA', '', 'AV CARLOS IZAGUIRRE 900', '', '0526 / 485-2344', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('M. JORGE E. TATAJE WILCOX', 'bbv-gorgi@terra.com.pe', 'LOS FICUS 376', '', '441-7993', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MANUEL VILLAR', '', 'JOSE PARDO 502', '', '4466098', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARTIN GALLO ELIAS', '', 'AV. DOS DE MAYO 1421 URB. ORRANTIA ', '', '721-1506', '97482951 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA ISABEL YOKOHAMA', '', 'AV. CAQUETA 1200', '', '381-0294', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MENDOZA PALOMINO SONIA', '', 'PASEO DE LA REPUBLICA 1541', '', '252-4697', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('NELLY HIGA HIGA DE TAMASHIRO', '', 'JR DE LA UNION 748 CERCADO DE LIMA', '', '428-5763', '4466098 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ROSA TAMASHIRO TAMASHIRO', '', 'AV ALFONSO UGARTE 1358', '', '423-6539', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SONIA MENDOZA PALOMINO', '', 'AV. PASEO DE LA REPUBLICA 1541', '', '252-4797', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PEDRO CONDORI', '', 'D 22 ASOCIACION LA PLANICIE ', '', '3879396', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ILKO MARROQUIN', '', 'AV. LA MAR 2275 136A ', '', '833-4527', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JAIME DIAZ MEGO', '', 'JR. LUCAR Y TORRE 458 ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MATTHEW SMITH', '', 'PJ. AGUIRRE 150 DPTO. 403 ', '', '2522197', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SARA GOMEZ DE CHUQUIMBALQUI', '', 'JR. ORTIZ ARRIETA 757', '', '/  777198 (044)', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LUZ MARIA ELESPURU DE SEMINARIO', '', 'KIBUR 170  RINCONADA DEL LAGO', '', '3680941', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ROMY CORTEZ', '', 'CAL. BELLAVISTA 112A DP 2', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VILMA ARGUEDAS OLIVERA', '', 'AV. DEL AIRE 558 URB. SANTA CATALINA ', '', '224-0426', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('KARLA OBLITAS LOPERA', '', 'VIA CHILINA  S/N  ALTO SELVA ALEGRE  -   AREQUIPA', '', '054 -228452 /', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LOAYZA TAM JUANA', '', 'CALLE AUSEJO SALAS  119  - HUACHO', '', '2321252', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('COQUE OSSIO', '', 'MIRAFLORES', '', '812-6178', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('WILLIAM ALVARADO  AVILA', '', 'PUESTO 62 MCDO ZONAL PALERMO ', '', '251755', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MONICA TAMARIZ ALEMAN', '', 'ISMAEL BIELICH  895 - SANTIAGO DE SURCO', '', '9949-0794', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA TERESA GARCIA', '', 'CAL. GENARO CASTRO IGLESIAS 242 302 URB. AURORA ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARION JACOBSON', '', 'AV. DOS DE MAYO 1675 DPTO. 201 ', '', '4417945 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SANTIAGO VALLADARES MALLQUI', '', 'AV. ARGENTINA 3093 PAB.4,PASAJE 2, NUMERO 8 (MINKA)', '', '8147880', '4536828 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARILU FARFAN CAMPOS', '', 'ELIAS AGUIRRE  # 600', '', '(074) 233118', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JULIO CESAR NUÑEZ', '', 'CALLE MANUEL UGARTECHE 411  UR. SELVA ALEGRE', '', '054-204060', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CATALINA CHOZA', '', 'CALLE SAN JUAN  798', '', '3726003', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA ELENA GALJUF', '', 'CAL. 13 MZ.M LT.1 URB. RINCONADA ', '', '4362127', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('TEODORO QUIJADA MEDINA', '', 'COPERATIVA SAN JUAN DE SALINAS MZ L LOTE 11', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VICTORIA WIESSE', '', 'SALAMANCA  116', '', '9042998', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RUBEN ROMERO CARBAJAL', '', 'CMDTE. ESPINAR  798', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JOSE ALFREDO BULLARD', '', 'CAL. JORGE BUCKLEY 227 URB. SAN ANTONIO ', '', '459848 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ALDO CASTAGNOLA B', 'aldo_castagnola@hotmail', 'AV. REPUBLICA DE PANAMA  258 - BARRANCO', '', '477-0111', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BUSE BAZO DE MADUEÑO MARIA LUISA VICTORIA', '', 'ERNESTO PLASCENCIA 350 -SAN ISIDRO', '', '4635329 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JAVIER W.CHAN UNG', '', 'AV. UNIVERSITARIA 697', '', '5661104 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JANET PEÑALOZA RIVERA', '', 'SAN JUAN DE MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MILENKA OLARTE', '', 'PJ. PORTO BELLO 155 ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('EUGENIO CHAIÑA ALIAGA', '', 'GENARO NUMA LLONA 260  ZONA A', '', '4661521 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LESLY GUEROVICH', '', 'LAS BAHAMAS 119 URB. SOL DE LA MOLINA', '', '20847/9919-8129', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA DEL CARMEN COSTANZA CAVALCANTI', '', 'AV. ANGAMOS OESTE 457 ', '', '4213597', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RINA GUIANELLI ARCE', '', 'SAN MARTIN 812 TACNA', '', '4461597', '726153 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LUIS ROCCHETTI MORRIS', '', 'CAL. SAN MARTIN 812 ', '', '741853 ', '711337 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GLORINDA PALPA SOTO', '', 'NICOLAS DE PIEROLA SUR 2248', '', '2440213 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VERONICA CORDOVA RUIZ', '', 'AV. LA ENCALADA 795 CC. MONTERRICO', '', '435-4249', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('AMELIA FORSYTH', '', 'CAL. BLAS CERDEñA 321 URB. STA CRUZ DPTO. 302 ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('AMELIA FORSYTH  DE CAMINO', 'AMELIAFORSYTH@HOTMAIL.COM', 'LOS MANZANOS 264   G-ALTOS', '', '2077 - 97225072', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DUSAN LUKFIC JIBAJA', '', 'VENTEDERIO 248 OLLANTAYTAMBO', '', '084-204048', '235078 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARGARITA PHANG', '', 'URB. EL CUADRO E-63', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('EMMA JELICIC DE LEON', '', 'CAL. ALBERTO DAVILA D 2 URB. LA CALERA DE LA MERCED ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('HUGO FERNANDEZ CARRANZA', '', 'JR. FRANCIA 954', '', '386-2262', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CLAUDIA VELARDE ARNAIZ', '', 'AV. LA ROSA TORO 1188', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ISABEL MORALES MARQUEZ', '', 'CALLE DOS N¦116 DPTO 101', '', '962 / 9945-0825', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VARGAS REYES ISOLINA', '', 'AV. LA MAR 391 SANTA CRUZ', '', '441-1026', '4483247 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA ELENA ROUILLON', '', 'JR. ANTONIO ENCINAS 141 URB. EL ROSEDAL ', '', '444-7004', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ELOISA RUIZ DE LIZARME', '', 'AV. TOMAS MARSANO 513 - A', '', '4755840', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RICARDO CAVENECIA', '', 'ANDREA DEL SARTO 260', '', '448-0669', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('HILDA MAURA AQUINO AQUINO DE JORGE', '', 'C 15 A.H. SOMOS LIBRES ', '', '459-7581', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JOSE BARRUETO SANCHEZ', '', 'SANTA VICTORIA LOS ALAMOS 169 - CHICLAYO', '', '074-270744', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('REYNALDO ZAMORA VIDAL', '', 'PIEROLA 513- BARRANCO', '', '477-1346', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('EUGENIO CHAIÑA ALIAGA', '', 'GENARO NUMA LLONA 260 .- SAN JUAN DE MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MIRIAN ESQUIVEZ ESPINOZA', '', 'MZ B LT. 48 REPUBLICA FEDERAL ALEMANA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARMEN MARILU FARFAN CAMPOS', '', 'ELIAS AGUIRRE  600  -  CHICLAYO', '', '074-233118', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLA RIBEIRO FLORES', '', 'ALM. LA ENCANTADA URB. LA ENCANTADA MZA. B LOTE. 03B ', '', '254-3482', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LUCIO SALAZAR PROEBSTER', '', 'CAL. JOSE D.ANCHORENA 010 DPTO. 801 ', '', '2644134 ', '98782427 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ARMANDO TAFUR CUNZA', '', 'MALECON ALMIRANTE GRAU 983 CHORRILLOS', '', '251-8109', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ANTONIA CENTENO JAIME', '', 'AV. SURCO 756 - URB. LA VIRREYNA', '', '224-3340', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CAROLINA SIFUENTES', '', 'AV. LA REPUBLICA 895', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ELENA BAZAGOITIA VILLAVICENCIO', 'ROSELENCHOCOLATES@MSN.COM', 'CALLE 9 # 415 MONTERRICO NORTE SAN BORJA', '', '436-9078', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOS CUENTAS', '', 'JR. PEDRO PAULET 454 URB. INGENIERIA ', '', '9933-3840', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LOPEZ VALERIANO JUAN', '', 'JR. LAS ALHUCEMAS 1194 URB. LAS FLORES ', '', '458-3642', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('KARLMANN PIZARRO ARANCIBIA', '', 'SECTOR1 K 01 GRU. 22 ', '', '2920925', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JAVIER MORENO CARRASCAL', '', 'AV. AVIACI+N 3362 SAN BORJA', '', '225-4059', '271-0160', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA ELENA B. DE GARLAND', '', 'CAL. CARLOS GRAñA 150 DPTO. 3B', '', '4214061', '98193010 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ORESTES GUIBU', '', 'AV. PALERMO 270-286 - LA VICTORIA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GUTIERREZ  CONTRERAS VICENTE PEDRO', '', 'AV. LAS AMERICAS 1428 URB. SANTO DOMINGO - LA VICTORIA', '', '472-2771', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RAFAEL CEREGHINO MORRIS', '', 'JR. LIBERTAD 1232 MAGDALENA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA ELENA AROSEMENA', 'MARICAB@TERRA.COM.PE', 'TOMASAL # 350 - MONTERRICO', '', '344-0630', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOS GUTARRA MECHAN', '', 'CAL. F.BARRETO 527 URB. MONTE CARMELO ', '', '224-1905', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CASTELLANO RODRIGUEZ GUSTAVO ADOLFO', '', 'AV. LAS BALSAS 115- URB. SN JUAN BAUTISTA - CHORRILLOS', '', '405328 ', '405328 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GUSTAVO CASTELLANO RODRIGUEZ', '', 'AV. LAS BALSAS  115  URB. SAN JUAN BAUTISTA-VILLA-CHORRILLOS', '', '2542813', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BENAVIDES LE JUEZ JOSEFINA PAULETTE ADRI', '', 'CAL. TORRE TAGLE 301 ', '', '241-5684', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ESTRADA BALMELLI MARIELLA', '', 'CAL. 2-168 URB. LAS MAGNOLIAS - SURCO', '', '9904-2890', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ALEJANDRO GUEVARA MONTENEGRO', '', 'AV. NACIONES UNIDAS 1709 - CERCADO DE LIMA', '', '472  - 97255407', '4257472 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ORIHUELA GOMEZ RAUL', '', 'AV. NESTOR GAMBETTA 5333 ', '', '422-8006', '421257 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VERGARA BERNAL ELISVAN', '', 'ICA', '', '221294', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('TRUJILLO RAMIREZ GERARDO', '', 'JR. PLABLO BERMUDEZ 214 - OF.402 - JESUS MARIA', '', '431-7033', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BELINDA GARATE CHANG', '', 'AV VARGAS MACHUCA 556 ZONA B - SAN JUAN DE MIRAFLORES', '', '666243 ', '661362 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('OSHIRO ISHIRO MIGUEL', '', 'AV. LOS DOMINICOS 688 URB. EL CONDOR-CALLAO', '', '574-4067', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SONIA AMELIA MENDOZA PALOMINO', '', 'AV. PASEO DE LA REPUBLICA 1541 CHORRILLOS', '', '252-4797', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VARGAS PARIONA JORGE LUIS', '', 'AV. AVIACION 3790 URB. LA CALERA -  SURQUILLO', '', '449-9167', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PISANO FELICE RICARDO NICOLAS', '', 'CAL. LEONIDAS AVENDAÑO 220 7 URB. SAN ANTONIO ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JOSE URCIA', '', 'LOS ZAFIROS 165 URB. SANTA INES - TRUJILLO', '', '04420-4075', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GRACIELA BARANDIARAN', '', 'CAL. JOSE ANTONIO 130 URB. PARQUE DE MONTERRICO', '', '4376681', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JAVIER LOPEZ NU-EZ', '', 'JR. TEJADA 499 ', '', '2540481 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA ELENA BASAGOITIA', '', 'CALLE # 9 415- SAN BORJA', '', '436-9078', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GRIMANESA DEL SOLAR', '', 'LEONIDAS AVENDA-O 235 MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SUSANA GARCIA CONDORI', '', 'AV. LA PAZ # 1934 SAN MIGUEL', '', '578-3063', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARMEN DE VACCARI', 'f-vaccari@terra.com.pe', 'MIRAFLORES', '', '444-3281', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FELIX CARRASCO ROJAS', '', 'AV. JOSE CARLOS MARIATEGUI   204  - ATE-VITARTE', '', '3521181', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('NOLBER TOLEDO', '', 'PJ. 4 A.H. SAN JUAN BAUTISTA MZA. L LOTE. 14 ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PEDRO VARGAS MAZA', '', 'JR. BELGICA 1409 DPTO. 15 ', '', '98372437 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SUSANA HOLGUIN PAISS', 'chocolateglamour@hotmail.com', 'LAS JACARANDAS N¦ 134 URB. SANTA VICTORIA - CHICLAYO', '', '074-9612630', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MAX WINTERHALTER BRIVIO', '', 'parque Olaya 185 San Bartolo', '', '4487057', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('NOELIA EDITH MENDOZA ESTRADA', '', 'PSJE. EL CARMEN MZ. B LT 5', '', '4657928', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ISOLINA VARGAS REYES', 'cevichelared@hotmail.com', 'AV. LA MAR # 391 SANTA CRUZ - MIRAFLORES', '', '441-1026', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VICTOR HUGO VILCA', '', 'AV. SANTA ANA N 11 URB. LOS SAUCES ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GOMEZ Y LOPEZ JUAN CARLOS', 'lookcosbvirger@hotmail.com', 'JR. ABTAO # 1021 - HUANUCO', '', '51-2460', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ORIETTA VALLEJOS', 'oriettavallejos@hotmail.com', 'MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA LUCILA JORDAN PAEZ DE MELGAR', '', 'CAL. ALAMEDA DEL SERENO 156 URB. LA ENCANTADA DE VILLA ', '', '2541264', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('EVARISTA TOMAYLLA PAREDES DE GUARDIA', '', 'VICTOR MANTILLA # 264 - SURQUILLO', '', '445-2413', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('AUGUSTO TAMAYO', '', 'AV. REPUBLICA 460 03 ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('EDUARDO GUIBU', '', 'AV. BENAVIDES # 2518 - MIRAFLORES', '', '449-0804', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARI SALDAÑA BLANCO', '', 'AV. JAVIER PRADO ESTE # 998 - SAN ISIDRO', '', '421-5179', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SANDRA RIVA', '', 'VIA LACTEA 250 - MONTERRICO SURCO', '', '4368972', '4463410 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JORGE CRISOSTOMO ESPINO', '', 'PASEO DEL BOSQUE MZ. B LOTE 5 - SAN BORJA', '', '3723793 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ROCIO IVET DREYFUS PUERTAS', '', 'AV. SANTA CRUZ # 905 - MIRAFLORES', '', '461-3636', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ALANA QUINTANILLA', 'alana_quintanilla@pe.yr.com', 'AV. LA MAR #1975 DPTO 502 - PUEBLO LIBRE', '', '9883-9364', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JAVIER GARCIA URIARTE', '', 'CALLE LOS LIBERTADORES # 307 - AGUAS VERDES -TUMBES', '', '326-4088', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GREGORIO PAUL PEÑA GUTIERREZ', '', 'SECTOR 1 GRUPO 2 MZ E LOTE 3 - VILLA EL SALVADOR', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ELISA PEÑA HERRERA LEON', '', 'LA GOLETA # 231 - SURCO', '', '271-4896', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JUAN B.FLORES PALACIOS', '', 'AV. MEXICO # 120 - LA VICTORIA', '', '323-7467', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GISELLA BECERRA BRAZZINI', '', 'TENIENTE ROMANET # 285 - SAN ISIDRO', '', '442-0723', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIO JOSE MORENO ZUÑIGA', '', 'PROLONGACION ARICA  2494', '', '4255194', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ADRIANA IBARRA ESPINOZA', '', 'JR. DOMINGO CASANOVA # 326 - LINCE', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LUZ ELVIRA ESCALANTE CORTEZ', '', 'CALLE 3 # 295 URB. LIGURIA - SURCO', '', '268-4301', ' 9046809 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JEAN PIERRE NADAL', '', 'JIRON TANGAY # 140 -   NUEVO CHIMBOTE', '', '98394530', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LUISA VARGAS', '', 'PARDO DE ZELA # 764 - 413 - LINCE', '', '470-3379', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SANTOS RAQUEL PE-A HIDALGO', '', 'CALLE SARAGOZA # 160 - MAYORAZGO', '', '348-7715', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FILOMENA FLORES PALACIOS', '', 'AV. LUZURIAGA #1190 - HUARAZ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JOSE ANTONIO GALARZA FLORES', '', 'JR. VENEGAS SAN AMBROSIO 120 LT32 COO. VIV JOSE QUINONES ', '', '247-5232', '9328799 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GERMAN COTRINA DIAZ', '', 'DIEZ CANSECO #146 - MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('IGNACIO ALCORTA', 'ignacioalcorta@hotmail.com', 'MIRAFLORES', '', '', '835*6153', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PAMELA LOAYZA OSORIO', '', 'AV. LA PAZ # 476 DPTO F - SAN MIGUEL', '', '566-1833', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MIGUEL OSHIRO OSHIRO', '', 'AV. LOS DOMINICOS NRO. 688 URB. EL CONDOR - CALLAO', '', '274-4067', '99006398', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ROYAL PEREZ ARBULU', '', 'CAL. SOR MATE 397 URB. PRLG.BENAVIDES ', '', '273-2801', '244-7188', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARMEN FABIOLA PEREZ DODERO', '', 'SIMON SALGUERO # 486 - SURCO', '', '271-2749', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIAMALIA JORQUIERA NARANJO', '', 'CAL. BETANIA 150 URB. SANTA MARIA ', '', '360-3357', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VICTOR SALAS CAMPOS', '', 'AV BENAVIDES # 3695 - SURCO', '', '273-0828', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARMEN PEREZ DODERO', '', 'SIMON SALGUERO # 486 - SURCO', '', '271-2749', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GINO TANTALEAN ALTRISTA', '', 'CALLE TACNA # 494 - MIRAFLORES', '', '4479731', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIELLA ESTRADA BALMELLI', '', 'CALLE DOS #168 URB LAS MAGNOLIAS-  SURCO', '', '445-9625', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ORME-O RIOS MARIA TERESA', '', 'AV. NICOLAS AYLLON 856 - LA VICTORIA', '', '3241356', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LA TORRE CHICANA GENSLER', '', 'AV. GRAU 1211', '', '5608196', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ESPEJO VASCONES OLGA ROSA', '', 'JR. LADISLAO ESPINAR 491 CASCO URBANO ANCASH', '', '327359 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VARGAS GUIZADO RICARDO', '', 'CAL. 9 URB. LOS VI±EDOS MZA. M LOTE. 23 - COMAS', '', '536-3436', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SHARON NORIEGA', '', 'AV. ALAMEDA DEL CORREGIDOR 260 URB. LA ENCANTADA ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA RAMOS RAMOS', '', 'AV. AREQUIPA 4670  -  MIRAFLORES', '', '4468041 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SEGUNDO SOBERON CARRANZA', '', 'SAN MARTIN DE PORRES', '', '568-3577', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ROGER PEREZ ARBULU', '', 'SIMON SALGUERO # 625 - SURCO', '', '273-2801', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RICARDO VARGAS GUIZADO', '', 'CALLE LAS CAMELIAS 100 - COMAS', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RUIZ CARBAJAL MARIA ELENA', '', 'AV. JAVIER PRADO 5332 RES. MONTERRICO', '', '437-7612', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GARCIA BEDOYA ASERVI DE DALMAU ANGELICA', '', 'AV. NUNEZ DE BALBOA 530', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SEN LOO ALEJANDRO VALENTIN', '', 'JR. UCAYALI 561  - LIMA', '', '428-5016', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RIOFRIO DE LEIGH MARIA CECILIA', '', 'AV. SULLANA 266 -2 PIURA', '', '372-7183', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CASTILLO MENDIVIS SANTIAGO RAFAEL', '', 'JR. RECUAY 138 DPTO. 22 - BRE-A', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CHANG CHIANG DE LAM LUCY KUAILIN', '', 'CAL. ALFREDO ICAZA 214 URB. SAN ROQUE  - SURCO', '', '268-9679', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CHLIMPER ACKERMAN JOSE', '', 'JR. MARISCAL MILLER 2170 - LINCE', '', '470-0033', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GUZMAN LEON CARMEN', '', 'CAL. JOSE NEYRA 152 URB. LA CALERA DE LA MERCED', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FRANCO RIBERA DE ORTEGA MIRIAM RUTH', '', 'CAL. ENRIQUE CIPRIANI 239 URB. STA CATALINA', '', '261-8269', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('OSORIO LLOCLLA RAUL ERNESTO', '', 'URB. VILLA VICTORIA MZA. W LOTE. 9 - SURQUILLO', '', '793-6641', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GARCIA URIARTE JAVIER OSWALDO', '', 'A.H. LA CURVA MZA. G LOTE. 22 - TUMBES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CABEZAS ARELLANO LUIS ALBERTO', '', 'CAL. ANTUCOYA 132 URB.TAHUANTINSUYO - LIMA INDEPENDENCIA', '', '526-5584', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JORGE TELLO VILLALOBOS', '', 'MANUEL ASCENCIOS SEGURA 285', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MILAGROS', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIO HERRERA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOS TARAZONA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ELESPURU MORALES DE SEMINARIO LUZ M.', '', 'CAL. KIBUR 170 URB. RINCONADA DEL LAGO - LA MOLINA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DANISSA VALDIVIA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FARFAN CAMPOS CARMEN MARILU', '', 'JR. ELIAS AGUIRRE 600 CERCADO LAMBAYEQUE - CHICLAYO', '', '229388', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SILVIA REUSENS', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JACKY FULLER', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LUIS VICENTE DIAZ VEGA', '', 'CALLE INCARIO 132 -MONTERRICO SURCO', '', '4362856', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('THORNE RIOS DE HUBNER EMMA ROSA', '', 'AV. LA PLANICIE 820 URB. LA PLANICIE', '', '4792906', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CRISOSTOMO ESPINO JORGE', '', 'PJ. PASEO EL BOSQUE B 5 A.H. EL BOSQUE - SAN BORJA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CENTENO PILLACA CONSTANTINO', '', 'AII LT03 URB. LA ENCALADA - SANTA ANITA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARCELINO RIVERA LUNA', '', 'JR.COLLASULLO  478-SAN JUAN DE LURIGANCHO', '', '4890375', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('UGARTE DE ARCE BETTY MARCELA', '', 'AV. HIPOLITO UNANUE 155 - CUSCO WANCHAQ', '', '222712 / 246142', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('INES BALLON', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('TUNCAR ALVA JANET VIVIANA', '', 'AV. MANUEL DE LA TORRE 973 URB. LOS FICUS - SANTA ANITA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('EDWARD ABARCA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RIVERA LUNA MARCELINO FLORENTINO', '', 'JR. COLLASUYO 478 URB. ZARATE LIMA - SAN JUAN DE LURIGANCHO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ANA MARIA TAMAYO RUNCIE DE TREMOLADA', '', 'CAL.ARICOTA 150 URB. TAMBO DE MONTERRICO -SANTIAGO DE SURCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MASIAS MARROU MANUEL ESTUARDO', '', 'LA CALERA S/N FND. LA CALERA ICA CHINCHA ALTO LARAN', '', '265511', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MONTEVERDE VASQUEZ SOLIS TERESA', '', 'ALM. DE LOS VIRREYES MZA1 LT1 URB. LAS LOMAS DE LA MOLINA', '', '365-6878', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MEDRANO RODRIGUEZ NATALI', '', 'CAL. ALMAGRO 153 - CUSCO', '', '084-226859', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CAMASCA HERNANDEZ ELVA EDITH', '', 'BL. 44 401 URB. LAS CRUZETAS II - SANTIAGO DE SURCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MEZA PRIETO CARLOS', '', 'AV. SUCRE 1180 - PUEBLO LIBRE', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('TRUJILLO DE LA CRUZ ANTONIO', '', 'AV. LOS FRUTALES 566 URB. LOS CACTUS - LA MOLINA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JOSE VALERA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LAURA DE SORIA HONORATA', '', 'CAL. LOS CRISTALES 104 - AREQUIPA SOCABAYA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GONZALES ODRIOZOLA DE FIGARI PILAR', '', 'JR. CHACALTANA 492- MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ECHEVARRIA SILUPU GRIMANESA', '', 'CAL. LAS GARDENIAS 2656 URB. JARDIN LINCE', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CRUZ URBINA KELLY MARIBEL', '', 'AV. CHILLON URB. EL ALAMO MZA V1 LOTE 14 COMAS', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MENDOZA MENACHO MIGUEL OSWALDO', '', 'CALLE SANTA VERONICA 209 URB. PALAO - SAN MARTIN', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LOSSIO DE ESCUDERO WHU CARMEN ROSA CATALINA', '', 'CALLE LOS PINOS 438 URB. SANTA VICTORIA LAMBAYEQUE', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RUIZ DE SOMOCURCIO TABINI, ALVARO ALEJANDRO', '', 'BARRANCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ENRIQUE MANSILLA', '', 'MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ELIZABETH ATARA', '', 'SAN ISIDRO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA ELENA VINCES', '', 'SAN ISIDRO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARTHA CASTAÑEDA', '', 'MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOS BRUCE', '', 'aV. eL POLO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('YON WONG JUAN CARLOS', '', 'JR. CERRO RICO MZ S LOTE 17', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MOSTAJO DE AGRAMONTE MARIA ELENA DEL PILAR', '', 'CAL. URUBAMBA S/N EDIF. METEO II DPTO 202 AREQUIPA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CUEVA PALOMINO KATHY YOHANA', '', 'JR. LAS AMPOLAS 252 INDEPENDENCIA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VERONICA NAVARRO', '', 'SAN ISIDRO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ANA DE ROJAS', '', 'PUEBLO LIBRE', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FLEISCHMANN', '', 'AV. ARGENTINA 1227', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PAOLA VIGO PAZ', '', 'SANTA  ANITA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MAIZONDO QUIROZ HECTOR IVAN', '', 'AV. VICTOR A. BELAUNDE 113 - ICA CHINCHA PUEBLO NUEVO', '', '267117', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FERNANDEZ NOE MARCELO ARTURO', '', 'AV. CANADA 155 URB. SANTA CATALINA - LA VICTORIA', '', '3862262', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SUSANA LARPEL', '', 'SURCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JAIME RODRIGUEZ', '', 'VILLA MARIA', '', '9765-7961', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('EDUARDO FERREYROS', '', 'SAN ISIDRO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GAMBOA CASTRO LUIS HUMBERTO', '', 'JR. JORGE CHAVEZ NRO. 251 P.J. JOSE CARLOS MARIATEG - VILLA MARIA DEL TRIUNFO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('Kimiko Elizabeth Fujiy Takeda', '', 'Vicente de la Vega 800-812 Chiclayo', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DOMINGO CARRERA', '', '...', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LUIS VILLA', '', '123', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('AGUIRRE CONCHA PABEL ILICH', '', 'AV. SOL NRO. 453 - CUSCO ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ARICA CASTRO CONSUELO REBECA', '', 'NRO. 214 U.V. STA MARINA SUR - CALLAO', '', '4657452 / 5281144 ', '97221734', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SANDOVAL SARMIENTO FLORENTINO', '', 'AV. CIRCUNVALACION NRO. 1040 LIMA - LA VICTORIA', '', '324-9157', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CABEZAS ARELLANO MARCO ANTONIO', '', 'Av Huanacaure Nº 960 - Cuarta Zona - Tawantinsuyo', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('KIOTAKE TAMASHIRO', '', 'LIMA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ROCIO LEMEL', '', 'AVENIDA `PRINCIPAL 786', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GILBONIO GARCIA CLAUDIA TEODOSIA', '', 'AV. ARGENTINA NRO. 3093 INT. 61 (PABELLON4/CALLE2 MERC. MINKA) PROV. CONST. DEL CALLAO ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA XIMENA MARTINEZ PINILLOS DE MALAGA', '', 'MALECON CISNEROS 238-DPTO 202', '', '', '4473058', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CICCIA GABILLO DE SOLDI ANGELA CATHERINA', 'X EL MINISTERIO DE DEFENSA', 'AV. BOULEVARD NRO. 1052 URB. URB. SAN BORJA SUR ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARMEN POLO', '', 'CALLE VALENCIA 172- DPTO 202- LA MOLINA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('OTANI KAWAGUCHI LUIS', '', 'CAL. RODOLFO BELTRAN NRO. 208 URB. SANTA CATALINA - LA VICTORIA', '', '94049865', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LILIANA DEL PILAR HUANCAYO ROJAS', '', 'JR. VENEZUELA 852 CALLAO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GIOVANNA MAGGIOLO', '', 'CALLE JUAN DE LA FUENTE 285- SAN ANTONIO ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GONZALES DE FERNANDEZ ENCARNACION ESMERALDA', '', 'CENTRO COMERCIAL SUR PLAZA - BOULEVAR ASIA MZ Ñ TDA. 7', '', '284-4072', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JUAN WALTER MUÑOZ CIPRIAN', '', 'CALLE CLORINDA MATTO DE TURNER Nº 56 SAN JERONIMO CUSCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOS IRAZOLA', '', 'MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('NAVARRO DE LOS RIOS HUGO STEPHEN', '', 'JR. ABTAO NRO. 810 - LA VICTORIA', '', '444-4834', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ANA MARIA JULIA VEGA CASTILLA  DE LEON', '', 'TENIENTE ROMANET 135- INT. 93- URB. SANTA MONICA -5000400007SAN ISIDRO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PALOMINO HUAMAN PAULA', '', 'CUSCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('YLLA CHINO TORIBIO', '', 'AV. ANGAMOS ESTE 1113', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('HERRADA AVILA GROMER ERNESTO', '', 'CAL. ANTONIO BAZO NRO. 792A - LA VICTORIA', '', '324-2143', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RIGAHU EVENTOS Y CATERING', '', 'MANUEL ZELAYA 158', '', '99407185', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BANDA GONZALEZ FRANCISCO RAFAEL', '', 'AV. PASEO DE LA REPUBLICA NRO. 385 - LA VICTORIA', '', '4241467 / 4239706 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('URSULA GALIDIE', 'h', 'AV. ANGAMOS OESTE 1664', '', '440-1461', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ARATA O´CONNOR LUIS ALBERTO', '', 'JR. DOMINGO PONTE NRO. 537 DPTO. 201 - MAGDALENA DEL MAR', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SINCHE CALLUPE FERNANDO MANUEL', '', 'JR. SAN CRISTOBAL NRO. 105 (FTE A BATA RIMAC) PASCO - PASCO - CHAUPIMARCA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SILLAU HERRERA NAPOLEON PIERRE', '', 'AV. JAVIER PRADO ESTE NRO. 5250 INT. 50 CTRO COM LA FONTANA - LA MOLINA', '', '4341036', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('IVETTY SANCHEZ TELLO', '', 'MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LAUREANO FRAGA GINAMARY', '', 'AV. UNIVERSITARIA NRO. 1699 URB. SANTA EMMA -  LIMA', '', '565-6604', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DE BERNARDI URMENETA PAOLA GABRIELA', '', 'CAL. CORONEL ZEGARRA NRO. 283  - BARRANCO', '', '247-4157', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MERY CHECA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FRANCISCO ARANETA', '', 'CHORRILLOS', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CRUZ CHICHIZOLA GUSTAVO GUILLERMO', '', 'AV. LA PAZ 1232 - MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('OSTOLAZA SOLANO HECTOR ANTONIO', '', 'MZA. D LOTE. 20 URB. MARISCAL LUZURIAGA  - ANCASH - SANTA - NUEVO CHIMBOTE', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('IZQUIERDO GONZALES TERESA AIDA', '', 'AV. BERNARDO ALCEDO NRO. 363 (ENTRE LA 19 Y 20 DE AV AREQUIPA) - LINCE', '', '4712171', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MENDIOLA WILLIAMS PATRICIA', '', 'JR. SANTIAGO FIGUEREDO NRO. 130 - MIRAFLORES', '', '441-1060', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BOWDEN MASSA GUILLERMO JOSE', '', 'AV. PASEO LA CASTELLANA NRO. 919 - SANTIAGO DE SURCO', '', '9655-3732', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIE FRANCE SUTO', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FAJARDO PALACIOS DE RIVERA SILVIA NOEMI', '', 'CAL. LUIS VALERA Y ORBEGOSO NRO. 130 - SURQUILLO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA LOHMANN', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RUTH ANDRADE', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LOPEZ MEDIAVILLA PAUL', '', 'CALLE AUSANGATE 510- MARANGA SAN MIGUEL', '', '561-1637', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LLAQUE CACHO WALTER NAPOLEON', '', 'JR. AMAZONAS NRO. 758 CAJAMARCA - CAJAMARCA', '', '822602 / 827911 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BORDA SOUTHALL KIA APRIL', '', 'CAL. BERLIN NRO. 333 - MIRAFLORES', '', '9813-2818', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FREDY HALBICH', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CASSINELLI TABINI LUISA MARCELA', '', 'CAL. -LAS TURMALINAS NRO. -122 DPTO. -201 URB. -CLUB GOLF LOS INCAS - SANTIAGO DE SURCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BECERRA ALFARO EDUARDO GONZALO', '', 'AV. 28 DE JULIO NRO. 1328 - MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BARRIENTOS GONZALES BENJAMIN CARLOS', '', 'CAL. CALLE 10 NRO. MZM1 INT. LT10 URB. CANTO NUEVO - SAN JUAN DE LURIGANCHO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ROSARIO NEGRON', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RAFAEL ZAPATA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FILOMENO ALFAGEME GISELLA MARIA', '', 'CAL. LAS CAMELIAS NRO. 951 URB. LAS PALMERAS DEL GOLF - LA LIBERTAD - TRUJILLO ', '', '271-1661', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('HILDA ROCIO PALOMINO COTRINA', '', 'JR. CHINCHA NRO. 462 URB. MESA REDONDA - SAN MARTIN DE PORRES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VELASQUEZ CASTRO VIVIANA LUCIA', '', 'CAL. MANUEL DE FALLA NRO. 101 URB. SAN BORJA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RAUL GUTIERREZ', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PAMELA GARCIA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ACOSTA DE MENDOZA LILY', '', 'PJ. LAS FLORES NRO. 224 SAN MARTIN - SAN MARTIN - LA BANDA DE SHILCAYO', '', '522225 / 524236 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ARMAS SOLF ALFREDO ALFONSO TORIBIO', '', 'CAL. LOS EUCALIPTOS NRO. 665 - LIMA - CHACLACAYO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VARGAS RIVERA DE NORIEGA ROSA CRISTINA', '', 'AV. BRASIL NRO. 3752 LIMA - LIMA - MAGDALENA DEL MAR', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BARRIOS IPENZA HUGO AUGUSTO', '', 'AV. SAN CARLOS NRO. 896  JUNIN - HUANCAYO - HUANCAYO', '', '200048 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DONGO AVALO JOSE RAMON', '', 'AV. ELVIRA GARCIA GARCIA NRO. 490 URB. LOS PARQUES LAMBAYEQUE  - CHICLAYO', '', '074-271457', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('Monica Suarez', '', 'Copacabana150 Sol de la Molina', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('Jesús Fonseca', '', 'La Floresta 319 - Camacho - Surco', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('Carlos Yagi', '', 'Cruz del Sur 415 - Dto. 501 Golf Los Inka - Monterrico', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CESAR', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JHORDANN', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DANIEL DIEZ', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SANDRA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FEIJOO AMPUERO CARLA FIORELLA', '', 'JR. ARNALDO MARQUEZ NRO. 1629 (ALT. CDRA.15 DE AV.BRASIL) LIMA - LIMA - JESUS MARIA', '', '463-9625 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('HENRY JARA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SUSANA BEDOYA', 'susanab', 'MIRAFLORES', '', '241-0327', '99665981', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BLANCA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('AQUINO ZEVALLOS EMANUEL FRANCISCO', '', 'JR. JACINTO BENAVENTE NRO. 269 URB. CIUDAD Y CAMPO - RIMAC', '', '4818545', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CHAVEZ ESPINOZA RUBEN DARIO', '', 'AV. CONQUISTADORES NRO. 299 - SAN ISIDRO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SOLOGUREN MARTINEZ WILFREDO FEDERICO', '', 'PROLONG. IQUITOS NRO. 1599  - LINCE', '', '445-1975', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GONZALEZ DIAZ EDWAR', '', 'AV. VIA DE EVITAMIENTO SUR NRO. 2486 BR LA COLMENA BAJA - CAJAMARCA ', '', '342-620 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('WALTER CACERES', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARMEN', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RUBY SANDOVAL', '', 'MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('KONG ALCANTARA BRAULIO R', '', 'SECTOR F MZA. L LOTE. 26 ASOC.VIV.LOS ANGELES - ATE', '', '4943560 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CASANA ZAMORA MERCEDES CLARA', '', 'AV. AYACUCHO NRO. 1339 URB. LIGURIA - SANTIAGO DE SURCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VALENCIA ORELLANA BERTHA ERNESTINA', '', 'JR. HIPOLITO UNANUE NRO. 1534 INT. 301 URB. SAN PABLO - LA VICTORIA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARCELEN FLORES ALONSO ALBERTO', '', 'CAL. JORGE BUCKLEY NRO. 263  - MIRAFLORES', '', '243-0166', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RENATO PERALTA', '', 'MIRAFLORES', '', '9826-8781', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIBEL SANCHEZ', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('INDIRA VILDOSOLA', 'indiravildosoab@yahoo.com', 'PASEO DE LA CASTELLANA 771 - SURCO', '', '271-6392', '9826-0322', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MORALES MEJIA EMILIA IRENE', '', 'CAL. DOMINGO ELIAS NRO. 839 LIMA - LIMA - SURQUILLO', '', '9323-9321', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MILAGROS', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BAYLON ESCOBAR GIOVANNA GLORIA', '', 'PUTUTOS NRO. 201 ZARATE LIMA - LIMA - SAN JUAN DE LURIGANCHO', '', '4958449 / 96808873', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GINO FARFAN', 'gefeo@hotmail.com <gefeo@hotmail.com>', 'LIMA', '', '423-6180', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BRACAMONTE MANTILLA JUAN JULIO', '', 'CAL. LOS OLIVOS NRO. 503 LA LIBERTAD - TRUJILLO - HUANCHACO', '', '044-461773', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('NAKAHODO NAKAHODO JOSE ALFREDO', '', 'CAL. LOPEZ DE ZUNIGA NRO. 244 LIMA - HUARAL - CHANCAY', '', '377-1009', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ANA CECILIA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('AQUILES BERNEDO UDAMAR', '', 'CAL. LA HONRADEZ NRO. 639 URB. PRO 1ERA ETAPA  - LOS OLIVOS', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PATRICIA VALDIVIA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VICUÑA ASTUHUAMAN PEDRO MIGUEL', '', 'CAL. MADRE DE DIOS NRO. 270 URB. SANTA PATRICIA 2DA ETAPA - LA MOLINA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JULS CATERING', '', 'LIMA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('YONG CHONG CARLOS ARTURO', 'MILAGROS', 'AV. NICOLAS DE PIEROLA NRO. 1631 INT. 201  - LIMA', '', '328-1834', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SANDRA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CASA CARTAGENA', '', 'CUSCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MICHAEL', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ROJAS PEREDO GLADIS ESTEFANIA', '', 'AV. BRASIL NRO. 1697 URB. FUNDO OYAGUE LIMA - LIMA - JESUS MARIA', '', '786-5388', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GONZALES VEGA CARLA FABIOLA', '', 'AV. JOSE RAMIREZ GASTON NRO. 257 URB. LA AURORA - MIRAFLORES', '', '271-5089', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SOCIEDAD HOTELERA LOS TAJIBOS S.A.', 'ecardona@lostajiboshotel.com', 'AV SAN MARTIN NO.455', '', '591-342-1000', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PATRICIA BENZA', '', 'CEDRONES 264 - URB.CIRIUS LA MOLINA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DE PIEROLA Y DE AVILES DIANA LUCIA SYLVIA', '', 'CAL. ANTERO ASPILLAGA NRO. 435  - SAN ISIDRO', '', '9629-4777', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('EDUARDO VERA', '', 'LIMA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ALVA TORRES BARDONIO', '', 'CAL. 1 ESTE NRO. 749 URB. CORPAC  - SAN ISIDRO', '', '2241168 / 93876665', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GIANCARLO', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JORGE GUZMAN', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('WILLIAN LOPEZ', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CLELIA CABRAL AVILA', '', 'CL. JUPITER NO.15 SAN ROQUE- SURCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BRUCE', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SALINAS LLANOS CARLOS ANTONIO', '', 'CAL. TIAHUANACO NRO. 132 URB. MARANGA - ET. 4 LIMA - LIMA - SAN MIGUEL', '', '5622262 / 97709101 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARLENY SALINAS', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FABIOLA VIGIL', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VEGA ARMAULIA JUAN CARLOS', '', 'JR. PIEROLA NRO. 448 CERCADO PUNO - SAN ROMAN - JULIACA', '', '(051)9518-92528', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PILAR BALTA', '', 'MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ZAMBRANO GARCIA SILVIA RAQUEL', '', 'JR. SAN MARTIN NRO. 220 SAN MARTIN - SAN MARTIN - TARAPOTO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ESPINOZA OCHAVE GREGORIO', '', 'CAL. DOMINGO ELIAS NRO. 839 LIMA - LIMA - SURQUILLO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FABRICIO´S CATERING', 'marielaheysen@fabricios.com', 'LIMA', '', '271-3714', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MIRKO LUCIANO BETANCOUR ANCHISSI', 'mirkobetancour@hotmail.com', 'ENRIQUE SALAZAR BARRETO 234 - SURCO', '', '271-7072', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARISELLA', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ARATA O´CONNOR LUIS ALBERTO', '', 'JR. DOMINGO PONTE NRO. 537 DPTO. 201 - MAGDALENA DELMAR', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ULISES VIGO', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FELIPE TORRES VARGAS', '', 'MZA. F LOTE. 58 URB. LOS CIPRESES ANCASH - SANTA - NUEVO CHIMBOTE', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('IVONNE EGUES', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CHAVEZ ESPINOZA RUBEN DARIO', '', 'AV. CONQUISTADORES NRO. 299 LIMA - LIMA - SAN ISIDRO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('PALACIOS MANRIQUE ZOSIMO GAUDENCIO', '', 'AV. ALMTE MIGUEL GRAU NRO. 1069 BARR ALTOS LIMA - LIMA - LIMA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GUSTAVO ALONSO VALCARCEL BELLO', 'gustavo.valcarcel@gmail.com', 'CAL. LOS AVIADORES NRO. 108 DPTO. 301 LIMA - LIMA - SANTIAGO DE SURCO', '', '7054400', '997932113', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BENDEZU TORRES ALBERTO ELIAS', '', 'JR. LOS FORESTALES NRO. 563 URB. RESIDENCIAL INGENIEROS  - LA MOLINA', '', '265-5875', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FELIX', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MIRANDA SANTUR YANINE AURORA', '', 'CAL. SAENZ PENA NRO. 2244 INT. B URB. LATINA LAMBAYEQUE - CHICLAYO - JOSE LEONARDO ORTIZ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ATIN CAMPOS', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('AELYN PEREZ', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VARGAS CRUZ SANTOS OSCAR', '', 'CAL. SANTA CATALINA ANCHA NRO. 366A CUSCO - CUSCO - CUSCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MUÑOZ AQUINO TANIA EMILIA', '', 'MCAL.CASTILLA NRO. 449 PLAYA RIMAC PROV. CONST. DEL CALLAO ', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CESAR ALEJANDRO DIAZ BARANDIARAN ', 'aledija@yahoo.com', 'CAL. FRANCISCO DE ZELA NRO. F2 INT. 18 URB. LOS PROCERES LIMA -SANTIAGO DE SURCO', '', '2741457', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GIOVANNA GLORIA BAYLON ESCOBAR ', '', 'PUTUTOS NRO. 201 ZARATE  - SAN JUAN DE LURIGANCHO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values (' JUAN ISAAC  ORIHUELA ARROYO', '', 'JR. LIMA NRO. 596 JUNIN  - TARMA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('EMILIA BUENDIA LAINEZ DE CASTRO ', '', 'JR. BATALLON CALLAO NRO. 643 URB. LAS GARDENIAS- SANTIAGO DE SURCO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('LOURDES GUADALUPE JURADO LIZANO', '', '-', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VICTOR RAUL YARA KIYAN ', '', 'AV. CANADA NRO. 3296 SAN BORJA - SAN BORJA', '', '2658129', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JORGE HERNANDEZ', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ALEXIS RAMIREZ', 'mardecopas1980@hotmail.com', 'MIRAFLORES ', '', '462-1562', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JORGE ORREGO VARGAS', '', 'CAL. M.AGUSTIN GAMARRA NRO. 279 PUEBLO LIBRE - PUEBLO LIBRE (MAGDALENA VIEJA)', '', '460-6313', '999960066', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ENRIQUE LUIS RODRIGUEZ DEL RIO', '', 'CAL. SANTA ISABEL NRO. 220 URB. MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('HIDALGO LAMA OSCAR EDDIE', '', 'AV. LOS CONSTRUCTORES NRO. 156 INT. TDA2 URB. LAS ACACIAS LA MOLINA', '', '3489664 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('marino pareja ', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SABINA DE SZYSZLO GHEZZI ', '', 'CAL. ALCANFORES NRO. 1255 INT. 4 MIRAFLORES', '', '4456844 / 94046179 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JORGE EDUARDO GUZMAN SANDOVAL', '', 'JR. LANQUI NRO. 364 URB. TUPAC AMARU SAN LUIS', '', '3234192 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VANESSA ALEXANDRA JAUREGUI NIÑO DE GUZMAN', '', 'CAL. ALFREDO I LEON NRO. 190 MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('INGRID SCHILDER MONTJOY  ', '', 'SAN ISIDRO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA DEL PILAR GUTIERREZ OVIEDO ', '', 'NRO. R INT. 14-A LOTIZACION CASABLANCA - PACHACAMAC', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values (' MARIA DEL ROCIO GABRIELA REYES DE AITA', 'eventoschio@hotmail.com]', 'CAL. JOSE QUINONES NRO. 16 LAMBAYEQUE - CHICLAYO - PIMENTEL', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA PARI CHOQUE ', '', 'CAL. JOSE ROSA ARA NRO. 1903  TACNA', '', '(052)414582', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SILVANA NUÑEZ', '', 'JIRON SANTA PRISCA 125 - LA MOLINA', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('FERNANDO APAESTEGUI', '', 'MIRALFORES - ONO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('sandra mercado brios', '', 'Los colibries 131 - San Isidro', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MAITE LOREDO', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('Cristian Casapia', '', 'Miraflores', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GUSTAVO', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RAVELLO DEL CARPIO MARTIN LUIS', '', 'JR. CESAR ESCOBAR NRO. 963 URB. S.J. - SAN JUAN DE MIRAFLORES', '', '2761993 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('TELMO PAULINO CABRERA CHUMPITAZ ', '', 'JR. LUIS VARELA Y ORBEGOSO NRO. 273  - SURQUILLO', '', '490122 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CARLOS ROGGERO ', 'CARLOS.ROGGERO@GMAIL.COM', 'MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SILVIA CHIONG', 'silvia@tanta.com.pe', 'MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('alesandra mannarelli', '', '', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA DILIA DONGO AVALO', '', 'AV. ELVIRA GARCIA Y GARCIA NRO. 696 URB. LOS PARQUES LAMBAYEQUE -CHICLAYO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ERIKA GISELLA RUIZ ABAD DE MOGOLLON', '', 'JR. ELEODORO ZEVALLOS NRO. 173 DPTO. E302 URB. VILLASOL III ETAPA LIMA -  LOS OLIVOS', '', '5523013 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('BULEJE OCHOA, ALFREDO', '', 'AV. ALAMEDA SUR MZA. J1 LOTE. 12 LIMA - LIMA - CHORRILLOS', '', ' 2549777  ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('MARIA INES PINTO', '', '446113- MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('Hania Ricketts', '', 'Las Clinas 190 - Casuarinas', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GISSELLE BENSA', '', '4606558-MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('RIVERA LUNA CESAR ARTURO', '', 'JR. PUNO NRO. 3720 URB. PERU LIMA - LIMA - SAN MARTIN DE PORRES', '', '5722281 / 992904760 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('NAVEA MOLINARI RENZO', '', 'AV. BERNARDO MONTEAGUDO NRO. 271 LIMA - LIMA - SAN ISIDRO', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('DIAZ RAMIREZ AURORA GUADALUPE', '', 'CAL. ELVIRA GARCIA Y GARCIA NRO. 696 URB. LOS PARQUES', '', '074228840', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SANTAYANA GUTIERREZ JUAN CARLOS', 'jc.chacha@hotmail.com', 'AV. ANGAMOS ESTE NRO. 2681 INT. N102 LIMA - LIMA - SAN BORJA', '', '2264059', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values (' LAZARTE ARIZOLA CARLOS JHONATAN', 'jla.25@hotmail.com', 'CAL. DANIEL ALCIDES CARRION NRO. 192 URB. SANTA LUZMILA LIMA - LIMA - COMAS', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('VALERIO HUAMAN SOCIMO', '', 'CAL. LOS LIRIOS MZA. N LOTE. 23 APV SOL DE STA ANITA LIMA - LIMA - SANTA ANITA', '', ' 3545104  ', ' 95695736 ', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('SINCHE CALLUPE FERNANDO MANUEL', 'manuelfresc1-@hotmail.com', 'JR. SAN CRISTOBAL NRO. 105 PASCO - PASCO - CHAUPIMARCA', '', '(063) 423237', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('GUERRERO VELASCO FREDESVINDA', '', 'AV. CUBA NRO. 898 INT. 704 LIMA - LIMA - JESUS MARIA', '', '4608254 ', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('CURICH MORENO TROIKA DE JESUS', '', 'JR. BOLOGNESI NRO. 755 LIMA - LIMA - MIRAFLORES', '', '', '', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('ACUY YANAC YISELA NEREYDA', 'ernestoblanco39@hotmail.com', 'AV. CAMINOS DEL INCA NRO. 3191', '', '2578658', '975132375', 0);
insert into prospecto(nombre, email, direccion, imagen, telcasa, telcelular, cliente) values ('JUAN AGUILAR', '', 'JR. VANGOGH 310 - SAN BORJA', '', '', '', 0);


insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('MARGARITA DE LA PIEDRA', 'margotcapie@hotmail.com', 'CAL. 24 DE JULIO 296 P.J. SIMON BOLIVAR ', '', '', '', '', 1);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('LUISA PARODI', '', 'TOMAS MARSANO  # 2124', '', '449-8998', '4498998 ', '', 2);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('SILVIA LUCILA ALBUQUERQUE F.', '', 'PASAJE JAEN  # 169  RAMON CASTILLA', '', '', '', '', 3);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('MARIA LUISA MONTES', '', 'LOS CASTA-OS 405 SAN ISIDRO', '', '690 // 264-2393', '', '', 4);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('HUMBERTO SATO', '', 'CAL. LA MERCED URB. LOS ALISOS MZA. D LOTE. 04 ', '', '5660290', '', '', 5);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('PATRICIA YESICA PEREZ HERRERA', '', 'LOS SAUCES  MZ. E  LT.  22   DPTO.  101', '', '', '', '', 6);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('RAMIREZ VILLALOBOS DELICIA MARGOT', '', 'AV. LUZURIAGA NRO. 834 ANCASH - HUARAZ - HUARAZ', '', '725689', '', '', 7);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('MERCEDES RIVAS PLATA', '', 'LOS TULIPANES    MZ.L  LT.  23', '', '', '', '', 8);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('ROLF KLINGENBERGER', '', 'AV. LA PAZ 1190', '', '444-8726', '', '', 9);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('CAROL M. BURNS', '', 'TUDELA Y VARELA 304', '', '441-8879', '536-7066 ', '', 10);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('JORGE BAERTL', '', 'GONZALES LARRA-AGA 180', '', '446-5994', '', '', 11);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('SOFIA FERREYRA', '', 'AV. AREQUIPA 4334  4to. PISO', '', '441-33-15', '', '', 12);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('DENNIS ACEVEDO', '', 'CALLE LOS ZAFIROS 150 BELLAVISTA', '', '918-9864', '', '', 13);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('KATTY RODRIGEZ', '', 'AV ESTACION S/N', '', '246-4024', '', '', 14);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('ARQ. GONZALO GARCIA', '', 'DIESCANSECO 481 ALT. CDRA. 56 DE PASEO DE LA REPUBLICA', '', '4453502', '', '', 15);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('JOSE AGUSTIN CAMPOS PALACIOS', '', 'AV BOLOGNESI 230', '', '9099438', '', '', 16);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('MARIELA BERTORINI', '', 'ALAMEDA DE LA MOLINA VIEJA 604', '', '495-10-43', '', '', 17);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('ANCCO CAYO JOSE BENITO', 'BAJA DEFINITIVA', 'APV.MIGUEL GRAU ZONA SUR MZA. L LOTE. 2 ', '', '4844595', '', '', 18);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('LECIC BALARIN VESNA', '', 'CAL. EL ALAMO 228 201 C.C. MONTERRICO ', '', '435-6499', '3723867 ', '', 19);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('MANUEL RIVERA TOYAMA', '', 'JAVIER PRADO OESTE # 114', '', '', '', '', 20);
insert into cliente (nombre, email, direccion, imagen, telcasa, telcelular, notas, idProspecto) values ('JUAN JOSE KONJA CARRASCO', '', 'AV. ECHENIQUE 140', '', '', '', '', 21);


insert into paciente (nombre, esterilizado, tamaño, actividad, peso, fchnac, especie, raza, genero, tiposangre, idCliente) values ('BOBY', 'S', 'mediano', 'muy jugueton', 25, '2009-08-05', 'Perro', 'Boxer', 'M', 'RH+', 1);
insert into paciente (nombre, esterilizado, tamaño, actividad, peso, fchnac, especie, raza, genero, tiposangre, idCliente) values ('Kafir', 'N', 'pequeño', 'agresivo', 13, '2007-08-15', 'Perro', 'Cocker Spaniel', 'M', 'RH+', 1);
insert into paciente (nombre, esterilizado, tamaño, actividad, peso, fchnac, especie, raza, genero, tiposangre, idCliente) values ('Stephany', 'N', 'pequeño', '', 7, '2003-10-23', 'Gato', 'Angora', 'F', 'RH+', 2);
insert into paciente (nombre, esterilizado, tamaño, actividad, peso, fchnac, especie, raza, genero, tiposangre, idCliente) values ('Brando', 'S', 'grande', 'dormilon', 40, '2004-12-30', 'Perro', 'Gran Danes', 'M', 'O', 3);
insert into paciente (nombre, esterilizado, tamaño, actividad, peso, fchnac, especie, raza, genero, tiposangre, idCliente) values ('FIGO', 'S', 'pequeño', 'manso', 8, '2007-08-05', 'Perro', 'Fox Terrier Toy', 'M', 'A', 4);
insert into paciente (nombre, esterilizado, tamaño, actividad, peso, fchnac, especie, raza, genero, tiposangre, idCliente) values ('OLIVER', 'S', 'mediano', 'muy jugueton', 16, '2010-10-05', 'Perro', 'Galgo Español', 'M', 'B', 5);
insert into paciente (nombre, esterilizado, tamaño, actividad, peso, fchnac, especie, raza, genero, tiposangre, idCliente) values ('ABELARDO', 'S', 'pequeño', '', 14, '2008-08-05', 'Gato', 'Persa', 'M', 'AB', 6);
insert into paciente (nombre, esterilizado, tamaño, actividad, peso, fchnac, especie, raza, genero, tiposangre, idCliente) values ('AMBROSIO', 'S', 'mediano', 'agresivo', 20, '2009-08-05', 'Perro', 'Husky Siberiano', 'M', 'RH+', 7);
insert into paciente (nombre, esterilizado, tamaño, actividad, peso, fchnac, especie, raza, genero, tiposangre, idCliente) values ('TASHIRA', 'S', 'mediano', 'timida', 16, '2012-08-05', 'Perro', 'Greyhound', 'F', 'A', 8);

insert into doctor (nombre, apellido, email, telefono, usuario, clave, perfil)  values ('Juan', 'Perez', 'j.perez@gmail.com', '346-7812', 'JPEREZ', 'JPEREZ', 'ADMIN');
insert into doctor (nombre, apellido, email, telefono, usuario, clave, perfil)  values ('Ricardo', 'Campos', 'rcampos@hotmail.com', '323-5333', 'RCAMPOS', '123456', 'USER');
insert into doctor (nombre, apellido, email, telefono, usuario, clave, perfil)  values ('Juan', 'Tapia', 'juanpablo@gmail.com', '346-8654', 'PABLO', '123', 'USER');

insert into cita (descripcion, telefono, direccion, fchcita, estado, idDoctor, idPaciente, idCliente) values ('Vacuna Anti-Rabia', '232-5444', 'CAL. 24 DE JULIO 296 P.J. SIMON BOLIVAR ', '2012-08-30', 'P', 1, 1, 1);
insert into cita (descripcion, telefono, direccion, fchcita, estado, idDoctor, idPaciente, idCliente) values ('Consulta', '543-8884', 'TOMAS MARSANO  # 2124', '2012-08-15', 'P', 2, 3, 2);
insert into cita (descripcion, telefono, direccion, fchcita, estado, idDoctor, idPaciente, idCliente) values ('Baño', '773-8998', 'CAL. LA MERCED URB.', '2012-08-30', 'P', 1, 6, 5);
insert into cita (descripcion, telefono, direccion, fchcita, estado, idDoctor, idPaciente, idCliente) values ('Vacuna Triple', '777-5554', 'LOS TULIPANES ', '2012-08-07', 'P', 3, 9, 8);

insert into citadetalle (cantidad, precio, idCita, idProducto) values (1, 120, 1, 5);
insert into citadetalle (cantidad, precio, idCita, idProducto) values (1, 20, 2, 14);
insert into citadetalle (cantidad, precio, idCita, idProducto) values (1, 50, 3, 13);
insert into citadetalle (cantidad, precio, idCita, idProducto) values (1, 20, 3, 11);
insert into citadetalle (cantidad, precio, idCita, idProducto) values (1, 30, 3, 9);
insert into citadetalle (cantidad, precio, idCita, idProducto) values (1, 150, 4, 8);

